#name: Coveralls
#
#on: push
#
#jobs:
#  coveralls:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Install deps
#        run: |
#          sudo apt update
#          sudo apt install libtesseract-dev
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.23
#
#      - name: Install dependencies
#        run: go mod download
#
#      - name: Run tests with coverage
#        run: go test -v -coverprofile=coverage.out ./...
#
#      - name: Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github_token: ${{ secrets.COVER_ALLS }}
#          path_to_coverprofile: ./coverage.out



name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
          sudo apt update
          sudo apt install libtesseract-dev
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          COVERALLS_TOKEN: ${{ secrets.COVER_ALLS }}
        run: goveralls -coverprofile=covprofile -service=github