name: Coveralls

on: push
#  push:
#    branches:
#      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install libtesseract-dev
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github_token: ${{ secrets.COVER_ALLS }}
          path_to_coverprofile: ./coverage.out